services:
  - type: web
    name: real-time-chat
    runtime: docker
    plan: free
    dockerfilePath: ./DockerFile
    dockerContext: .
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_CLERK_PUBLISHABLE_KEY
        sync: false
      - key: CLERK_PUBLISHABLE_KEY
        sync: false
      - key: CLERK_SECRET_KEY
        sync: false
      - key: MONGODB_URI
        sync: false